version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  app:
    image:  manoj20002/code-keeper:latest
    container_name: code-keeper
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_NAME: mydatabase
      DB_USER: admin
      DB_PASS: admin
      DB_HOST: db   # 👈 service name, not localhost
      DB_PORT: 3306
    depends_on:
      - db
